apiary.apib

Add documentation for aggregation URL (GET, ADD, DELETE)

---

apiary.apib

* Update image URL link from YelpCDN to birdeye's cloudfront.
* Set social profile URL to null.

Update yelp image URL and social profile URL

---

apiary.apib

Add new parameter aggregationSource for submit review API.

Add aggregatio source

---

apiary.apib

Remove "\t"

---

apiary.apib

Added SMB dashboard api documentation.

---

apiary.apib

removed \t

---

apiary.apib

2 new error code added for submit review api.

---

apiary.apib

customer checkin API updated

---

apiary.apib

typos corrected in get reviews API

typos corrected in get reviews API

---

apiary.apib

Corrected typo in get reviews API

Corrected typo in get reviews API

---

apiary.apib

Please review and merge this change.

Added Youtube URL for update and get API usage.

---

apiary.apib

Added email conversion report documentation.

---

apiary.apib

Added comments for optional field.

Added note for optional fields

---

apiary.apib

* Added featured review documentation for get reviews api.
* Added featured review documentation for update featured review api.

Add featured review documentation.

---

apiary.apib

reviews summary documentation added

---

apiary.apib

fixed description for type field in account signup

fixed description for type field in account signup

---

apiary.apib

Business public profile tab api Documentation

---

apiary.apib

@guptas Please review this change.

Sk add url profile tabs

---

apiary.apib

BIRDEYE-922: Add phone in API document to support phone.

---

apiary.apib

BIRDEYE-924: Update documentation for child business hierarchy

---

apiary.apib

updating the documentation to use https for url

---

apiary.apib

updating the examples to use https endpoint for API

---

apiary.apib

BIRDEYE-923:Reports Public api documentation

---

apiary.apib

@guptas Please review and merge.

Correct business spell in signup api

---

apiary.apib

@guptas Please review this change.

BIRDEYE-1379:Customer list public API documentation

---

apiary.apib

@guptas Please review these changes.

BIRDEYE-1788:Add missing header for API doc

---

apiary.apib

@guptas Please review these changes.

BIRDEYE-1853:Remove yelp reference

---

apiary.apib

BIRDEYE-1788: adding missing header info in the customer/all api

---

apiary.apib

BIRDEYE-1788: adding missing header info in the customer activity log api

---

apiary.apib

@guptas Please review and merge these changes.

BIRDEYE-1867:Show curl command for add and delete aggregation URL

---

apiary.apib

@guptas Please review these change.

BIRDEYE-2194:Delete customer API documentation

---

apiary.apib

@guptas @ameyavirkar Please review this change.

BIRDEYE-2669:update documentation for aggregation sourceId

---

apiary.apib

@ameyavirkar Please merge this PR.

Fix tab issue, tabs does not work and reflect content

---

apiary.apib

@guptas Please review these changes.

BIRDEYE-5011:get reviews api documentation update

---

apiary.apib

included businessId and uniqueUrls for documentation

---

apiary.apib

@guptas Added documentation for checkin response. Please review this change.

BIRDEYE-5139:Checkin response documentation

---

apiary.apib

Fix Aggregation Doc formatting

---

apiary.apib

@ameyavirkar : Please review bulk create business doc.

BIRDEYE-11148:Bulk Business create doc

---

apiary.apib

Revert "Birdeye 11184 doc"

---

apiary.apib

grammar fix

---

apiary.apib

@guptas : Please review this PR.

BIRDEYE-12318: Public api for competitors

---

apiary.apib

Added docs for API Key based survey list responses api.

sac-BIRDEYE-27528

---

apiary.apib

In ref to https://birdeye.atlassian.net/browse/BIRDEYE-66612 and https://birdeye.atlassian.net/browse/BIRDEYE-66762

Kontacto checkin tags

---

apiary.apib

@kamalatbe @sachmuchsachin Correcting the ? to & in the API url

BIRDEYE-73947 correcting the ? to &

---

apiary.apib

Revert "Added the add card detail api"

---

apiary.apib

Added InstagramURL key in Create and Update Listings Public API Documentation

BIRD-79092 : Added InstagramURL key

---

apiary.apib

Jira Link : - https://birdeye.atlassian.net/browse/BIRD-118128

Dimensions and Url Fix - Cover ImageUrl - Core

---

apiary.apib

Jira Link + Description : - https://birdeye.atlassian.net/browse/BIRD-118128?focusedCommentId=780405

Updated Cover Image Url (Core) 

---

apiary.apib

Enable messaging attributes (for Whatsapp and Text messaging) in the GBP

BIRD-124192 | FR -Enable messaging attributes (for Whatsapp and Text messaging) in the GBP

---

apiary.apib

Error message in case on createListings

BIRD-124192 | FR-  Error message in case on createListings

---

apiary.apib

Jira Link + Description : - https://birdeye.atlassian.net/browse/BIRD-141230

Custom Fields Api Changes

---

apiary.apib

Jira Link + Description : - https://birdeye.atlassian.net/browse/BIRD-156537

Custom Field Changes
